In [ ]:
import numpy as np
x = np.array([5, 1, 9, 8, 7, 2, 9, 3])

Method 1

In [ ]:
# Sum of all the elements of an array
# numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)[source]
x.sum()

44

Method 2

In [ ]:
# Minimum value among the elements of an array
# ndarray.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
x.min()

1

Method 3 

In [ ]:
#  Maximum value among the elements of an array
# ndarray.max(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
x.max()

9

Method 4

In [ ]:
# Minimum index value among the indexes of elements of an array
#numpy.argmin(a, axis=None, out=None)
x.argmin()

1

Method 5

In [ ]:
# Minimum index value among the indexes of elements of an array
# numpy.argmax(a, axis=None, out=None)
x.argmax()

2

Method 6

In [ ]:
# Logical "AND" operation among the elements of a boolean array
# numpy.all(a, axis=None, out=None, keepdims=<no value>)
np.all([False, True, True, True])

False

Method 7

In [ ]:
# Logical "OR" operation among the elements of a boolean array
# numpy.any(a, axis=None, out=None, keepdims=<no value>)
np.any([True, True, True, False])

True

Method 8

In [ ]:
# Setting all the elements of an array to 0
# numpy.zeros(shape, dtype=float, order='C')
a = np.zeros((50, 50))
np.any(a != 0)

False

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

Method 9

In [ ]:
#: Setting diagonally all elements as "1" in a square matrix
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
arr = np.eye(5,k=0)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#...continues: We can also specify other than square matrix but it would look like as below
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

Method 10 

In [ ]:
#diag: This function creates a two dimensional 
#array with all the diagonal elements as the given value
#and rest as 0 (in a square matrix).
arr = np.diag([1,5,3,7])
arr

array([[1, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 7]])

In [ ]:
#To get the diagonal elements in a two dimensional array we
#use diag as a funcion
np.diag(arr)

array([1, 5, 3, 7])

Method 11 

In [ ]:
# randint. This funciton is used to generate random number between a given range.
#numpy.random.randint(low, high=None, size=None, dtype='l')
arr = np.random.randint(1,10,3)
arr
#output would be any 3 number from 1 to 9

array([8, 2, 6])

Method 12 

In [ ]:
# rand: This function is used to generate random values  between 0 to 1
#The syntax is: 
#numpy.random.rand(d0, d1, ..., dn)
arr = np.random.rand(5)
arr
#Output may be any 5 numbers from 0 to 1

array([0.20085906, 0.43598384, 0.60957201, 0.81030221, 0.93500256])

In [ ]:
#...continues. We may generate random numbers in 2D array format as well
arr = np.random.rand(2, 3)
arr

array([[0.75083009, 0.03643402, 0.80440182],
       [0.98476786, 0.53100454, 0.95850766]])

Method 13

In [ ]:
# randn: This function is used to generate random values to 0 (zero). This may return positive or negative numbers as well.
#The syntax is:
#numpy.random.randn(d0, d1, ..., dn)
arr = np.random.randn(5)
arr
#Output may be any 5 numbers from centered to 0 (zero)

array([ 0.18033495,  1.37343346, -0.31034713, -1.30535918,  0.05131981])

Method 14

In [ ]:
# arange. There would be a starting point and an ending point along with the interval value.
# numpy.arange([start, ]stop, [step, ]dtype=None)
arr = np.arange(2,15,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
#...continues. If we do not specify the value it will automatically be incremented by 1
arr = np.arange(2, 14)
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Method 15 

In [ ]:
#sin. Print sine of one angle:
#numpy.sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'sin'>
np.sin(np.pi/2.)

1.0

In [ ]:
#...continues. Print sines of an array of angles given in degrees:
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

Method 16

In [ ]:
# Cosine element-wise.
#numpy.cos(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'cos'>
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

Method 17

In [ ]:
# tan
# numpy.tan(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'tan'>
from math import pi
np.tan(np.array([-pi,pi/2,pi]))

array([ 1.22464680e-16,  1.63312394e+16, -1.22464680e-16])

Method 18

In [ ]:
#round.
# numpy.round_(a, decimals=0, out=None)
np.round(16.055, 2), round(16.055, 2)  # equals 16.0549999999999997

(16.06, 16.05)

In [ ]:
a = np.array([-1.5, -1.3, -0.7, 0.9, 1.2, 1.4, 2.1])

Method 19

In [ ]:
# floor. Return the floor of the input, element-wise.
#The floor of the scalar x is the largest integer i, such that i <= x.
# numpy.floor(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'floor'>
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

Method 20

In [ ]:
# ceil. Return the ceiling of the input, element-wise.
#The ceil of the scalar x is the smallest integer i, such that i >= x.
# numpy.ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'ceil'>
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

Method 21

In [ ]:

#Return the truncated value of the input, element-wise.
#The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. 
#In short, the fractional part of the signed number x is discarded.
# numpy.trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'trunc'>
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

Method 22

In [ ]:

#Return the product of array elements over a given axis.
#The product of an empty array is the neutral element 1:
# numpy.prod(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
np.prod([])

1.0

In [ ]:
#...continues. when the input array is two-dimensional:
np.prod([[1.,2.],[3.,4.]])

24.0

Method 23

In [ ]:
#  cumsum. Return the cumulative sum of the elements along a given axis.
# numpy.cumsum(a, axis=None, dtype=None, out=None)
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.cumsum(a,axis=0)  # sum over rows for each of the 3 columns

array([[1, 2, 3],
       [5, 7, 9]])

Method 24

In [ ]:
# lcm. Returns the lowest common multiple of |x1| and |x2|
# numpy.lcm(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'lcm'>
np.lcm(17, 60)

1020

Method 25

In [ ]:
# gcd. Returns the greatest common divisor of |x1| and |x2|
# numpy.gcd(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'gcd'>
np.gcd(17, 60)

1

Method 26

In [ ]:
x = np.arange(4).reshape((2, 2))
x

array([[0, 1],
       [2, 3]])

In [ ]:
# transpose. Reverse or permute the axes of an array; returns the modified array
# numpy.transpose(a, axes=None)
np.transpose(x)

array([[0, 2],
       [1, 3]])

Method 27

In [ ]:
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4'); 
c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [ ]:
# capitalize. Return a copy of a with only the first character of each element capitalized.
# numpy.char.capitalize(a)
np.char.capitalize(c)

array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

Method 28

In [ ]:
c = np.array(['A1B C', '1BCA', 'BCA1']) 
c

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [ ]:
# lower. Return an array with the elements converted to lowercase.
# numpy.char.lower(a)
np.char.lower(c)

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

Method 29

In [ ]:
c = np.array(['a1b c', '1bca', 'bca1'])
c

array(['a1b c', '1bca', 'bca1'], dtype='<U5')

In [ ]:
#  upper. Return an array with the elements converted to upper.
# numpy.char.upper(a)
np.char.upper(c)

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

Method 30

In [ ]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [ ]:
# count. Returns an array with the number of non-overlapping occurrences of substring sub in the range [start, end].
#Calls str.count element-wise.
# numpy.core.defchararray.count(arr, substring, start=0, end=None) 
np.char.count(c, 'aA')

array([3, 1, 0])

Method 31

In [ ]:
#linspace. This function returns values between a given range and with a same gap between consecutive elements.
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
matrix = np.random.randint(1,4,9).reshape(3,3)
matrix

array([[2, 1, 1],
       [1, 2, 1],
       [1, 2, 1]])

Method 32

In [ ]:
np.min(matrix, axis=1) #finds row wise min

array([1, 1, 1])

Method 33

In [ ]:
np.max(matrix, axis=0) #finds col wise max

array([2, 2, 1])

Method 34

In [ ]:
np.sum(matrix, axis=1) #finds row wise sum

array([4, 4, 4])

Method 35

In [ ]:
np.cumsum(matrix) #finds cumulative sum

array([ 2,  3,  4,  5,  7,  8,  9, 11, 12])

Method 36

In [ ]:
np.random.seed(122)
arr = np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [ ]:
# shuffle. shuffle the array elements.
# numpy.random.shuffle(x)
np.random.shuffle(arr)
arr

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

Method 37

In [ ]:
# unique. displays unique number of the array.
# numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
np.unique(arr)

array([ 3, 10, 11, 13, 16, 17])

Method 38

In [ ]:
# argsort. prints the sorted index value wise ascending
# numpy.argsort(a, axis=-1, kind=None, order=None)
one = np.array([1,3,4,2])
one.argsort()

array([0, 3, 1, 2])

In [ ]:
x = [[1,2,3],[4,5,6],[7,1,0]]
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

Method 39

In [ ]:
# Return elements chosen from x or y depending on condition.
# numpy.where(condition[, x, y])
np.where(arr > 5)

(array([1, 2]), array([2, 0]))

Method 40

In [ ]:
# Counts the number of non-zero values in the array a.
# numpy.count_nonzero(a, axis=None, *, keepdims=False)
np.count_nonzero(arr)

8

In [ ]:
a = np.array([[1,4], [3,1]])
a

array([[1, 4],
       [3, 1]])

Method 41

In [ ]:
#  It is used to sort an array
a.sort(axis=1)
print(a)
a.sort(axis=0)
print(a)

[[1 4]
 [1 3]]
[[1 3]
 [1 4]]


Method 42

In [ ]:
#. Compute the variance along the specified axis.
# numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>)
a = np.array([[1, 2], [3, 4]])
np.var(a)

1.25

Method 43

In [ ]:
#  Split an array into multiple sub-arrays as views into ary.
#multiple sub-arrays as views into ary.
# numpy.split(ary, indices_or_sections, axis=0)[source]

x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
#...continues
x = np.arange(8.0)
np.split(x, [3,5,6,10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

Method 44

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# delete. Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].
# numpy.delete(arr, obj, axis=None)
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

Method 45

In [ ]:
a = np.array([[1,1],[2,2],[3,3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# Insert values along the given axis before the given indices.
# numpy.insert(arr, obj, values, axis=None)
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

Method 46

In [ ]:
A = np.diag([1.,2.,3.])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
# Flip array in the left/right direction.
# Flip the entries in each row in the left/right direction. Columns are preserved, but appear in a different order than before.
# Requires the array to at least 2-D.
# numpy.fliplr(m)
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

Method 47

In [ ]:
A = np.diag([1.0, 2, 3])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
#Does not require the array to be two-dimensional.
# Flip array in the up/down direction.
# numpy.flipud(m)
np.flipud(A)

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

Method 48

In [ ]:
# Inner product of two arrays.
# numpy.inner(a, b)
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

Method 49

In [ ]:
#. Return the sum along diagonals of the array.
# numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
np.trace(np.eye(3))

3.0

Method 50

In [ ]:
#  reciprocal. Return the reciprocal of the argument, element-wise.
#This function is not designed to work with integers.
# numpy.reciprocal(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'reciprocal'>
np.reciprocal(2.)

0.5

Method 51

In [ ]:
#. conjucate. Return the complex conjugate, element-wise.
# numpy.conjugate(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'conjugate'>
x = np.eye(2) + 1j * np.eye(2)
np.conjugate(x)

array([[1.-1.j, 0.-0.j],
       [0.-0.j, 1.-1.j]])